version: "3.8"
services:
  #caddy:
  #  image: caddy:2-alpine
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  volumes:
  #    - ${PWD}/Caddyfile:/etc/caddy/Caddyfile
  #    - ${PWD}/data/caddy:/data
  unifi-controller:
    image: linuxserver/unifi-controller:version-6.0.45
    environment:
      - PUID=1000
      - PGID=1000
      # - MEM_LIMIT=1024M #optional
    volumes:
      - ${PWD}/data/unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: "no"
  sendgrid-proxy:
    image: fgribreau/smtp-to-sendgrid-gateway:latest
    env_file:
      - ./env/unifi-controller.env
  plex:
    image: linuxserver/plex
    container_name: plex
    # network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= # https://www.plex.tv/claim/
    volumes:
      -  ${PWD}/data/plex/config:/config
      -  ${PWD}/data/plex/tv:/tv
      -  ${PWD}/data/plex/movies:/movies
    ports:
      - 32400:32400
    restart: "no"